# Generated by Django 5.0.2 on 2024-02-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
