# Generated by Django 5.0.2 on 2024-02-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online", "0003_category_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="image_url",
        ),
        migrations.AddField(
            model_name="animal",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="animal_pics"),
        ),
    ]
