# Generated by Django 5.0.2 on 2024-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online", "0004_remove_animal_image_url_animal_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="weight",
            field=models.DecimalField(decimal_places=1, default=99.9, max_digits=10),
        ),
    ]
